import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import { getHeaderData, getSideBarData } from "../../lib/api-server";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = cookies();
  const lang = cookieStore.get("lang")?.value || "vi";
  const headerData = await getHeaderData();
  const sidebarData = await getSideBarData();
 

  const data = {
    headerData,
    sidebarData,
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <>
        <Header data={data} lang={lang}/>
          <main>{children}</main>
          <Footer />
        </>
      </body>
    </html>
  );
}
